# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brosnan Chia
tagline:          ''
description:      'Hello there, I am a programmer based in Singapore!'
url:              https://broscew.github.io/
baseurl:          https://broscew.github.io/

author:
  name:           'Brosnan Chia'
  url:            https://www.linkedin.com/in/brosnanchia/

paginate:         5

# Custom vars
version:          Jekyll, Hyde Theme and hosted on Github.

github:
  repo:           https://github.com/broscew

