# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brosnan
tagline:          'WIP'
description:      'Hello there, I am a programmer based in Singapore and welcome to my site!'
url:              https://broscew.github.io/
baseurl:          https://broscew.github.io/

author:
  name:           'Brosnan'
  url:            https://www.linkedin.com/in/brosnanchia/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/broscew

